import path from 'path'
import dotenv from 'dotenv'
import { createClient } from '@supabase/supabase-js'

// .env.local permet de cacher les clés supabase
const envPath = path.resolve(process.cwd(), '.env.local')
dotenv.config({ path: envPath })

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('Missing Supabase environment variables. Create a .env.local with NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY')
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)

async function run() {
  console.log('Using Supabase URL:', SUPABASE_URL)

  const { data, error } = await supabase.from('recette').select('*').limit(5)

  if (error) {
    const msg = String(error.message || error)
    if (msg.toLowerCase().includes('does not exist') || msg.toLowerCase().includes('relation') || msg.toLowerCase().includes('42p01')) {
      console.error('La table `recettes` est introuvable dans votre base Supabase.')
      console.log('\nExécutez ce SQL dans le SQL Editor du dashboard Supabase pour créer la table et quelques exemples :\n')
      console.log('/* SQL à copier-coller dans Supabase > SQL Editor */')
      console.log(`\nCREATE TABLE public.recettes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  ingredients jsonb,
  steps text,
  created_at timestamptz DEFAULT now()
);\n`)
      console.log(`INSERT INTO public.recettes (title, slug, description, ingredients, steps) VALUES
('Cr\'epe', 'crepe', 'Cr\'epe classique', '["farine","oeufs","lait"]', 'M\'elanger, cuire ~1-2 min par c\'ot\'e.'),
('G\'ateau au chocolat', 'gateau-chocolat', 'G\'ateau moelleux au chocolat', '["chocolat","beurre","oeufs","sucre","farine"]', 'M\'elanger, cuire 25-30 min à 180°C.');\n`)

      console.log('Après création de la table, relancez ce script pour voir/insérer des données.')
    } else {
      console.error('Erreur lors de la requête :', error)
    }
    return
  }

  console.log('Table `recettes` trouvée. Exemples (jusqu\'à 5 lignes) :')
  console.log(data)

  if (process.argv.includes('--insert')) {
    const samples = [
      {
        title: 'Crêpes',
        slug: 'crepes',
        description: 'Crêpes classiques',
        ingredients: ['farine', 'oeufs', 'lait', 'sucre'],
        steps: 'Mélanger les ingrédients et cuire dans une poêle chaude.'
      },
      {
        title: 'Gâteau au chocolat',
        slug: 'gateau-chocolat',
        description: 'Gâteau moelleux au chocolat',
        ingredients: ['chocolat', 'beurre', 'oeufs', 'sucre', 'farine'],
        steps: 'Faire fondre, mélanger, cuire 25-30 min à 180°C.'
      }
    ]

    console.log('Insertion des recettes exemples...')
    const { data: insertData, error: insertError } = await supabase.from('recettes').insert(samples)
    if (insertError) console.error('Erreur à l\'insertion :', insertError)
    else console.log('Insert OK :', insertData)
  }
}

run().catch((err) => {
  console.error('Erreur inattendue :', err)
})
